name = "a0b_stm32g4_gpio"
description = "A0B: STM32G4 GPIO"
version = "0.2.0-dev"

website = "https://github.com/godunko/a0b-stm32g4-gpio"
authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["a0b", "embedded", "stm32", "stm32g4", "gpio", "exti"]

project-files = ["gnat/a0b_stm32g4_gpio.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
a0b_stm32f2_generic_exti = "*"
a0b_stm32g4 = "*"

[[actions]]
type = "test"
directory = "selftest"
command = ["alr", "build"]
